// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type DispatchResourceRequest struct {
	ResourceType string                 `json:"type"`
	Event        string                 `json:"event"`
	Spec         map[string]interface{} `json:"spec" validate:"required,dive,required"`
	Metadata     map[string]interface{} `json:"metadata,omitempty"`
}

type DispatchResourceResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type FetchAllResourcesRequest struct {
	ResourceType string `json:"resource_type"`
	Namespace    string `json:"namespace,optional"`
}

type FetchAllResourcesResponse struct {
	Code    int                      `json:"code"`
	Message string                   `json:"message"`
	Data    []map[string]interface{} `json:"data"`
}

type FetchResourceRequest struct {
	ResourceType string `json:"resource_type"`
	ResourceName string `json:"name"`
	Namespace    string `json:"namespace,optional"`
}

type FetchResourceResponse struct {
	Code    int                    `json:"code"`
	Message string                 `json:"message"`
	Data    map[string]interface{} `json:"data"`
}
